// Encuesta Grupo 2 · Estudiantes de 5° a 8° básico (v9 aprobada, 2/10/2026).
// El curso no se pregunta: sale de la credencial.
import type { Encuesta } from "./tipos";
import * as L from "./listas";
import { op } from "./listas";

export const estudiantes: Encuesta = {
  estamento: "E",
  titulo: "Encuesta para estudiantes",
  introduccion: [
    "¡Hola! Queremos saber qué piensas de tu escuela y cómo te gustaría que fuera en los próximos años.",
    "No es una prueba: no hay respuestas buenas ni malas y no tiene nota. Tu clave la sacaste al azar y nadie sabe cuál te tocó. Responde con sinceridad y no escribas nombres de personas.",
  ],
  minutos: 15,
  despedida: "¡Gracias por ayudarnos a construir tu escuela!",
  secciones: [
    {
      titulo: "Mi escuela hoy",
      preguntas: [
        {
          codigo: "E1",
          numero: 1,
          tipo: "unica",
          texto: "¿Sabes cuál es el lema de tu escuela?",
          opciones: L.CON_ESTUDIANTES,
        },
        {
          codigo: "E2",
          numero: 2,
          tipo: "escala",
          escala: "FRE",
          texto: "¿Con qué frecuencia te pasa esto?",
          indicacion: "Marca una opción por frase",
          grupos: [
            {
              items: [
                { codigo: "1", texto: "Me gusta venir a la escuela" },
                { codigo: "2", texto: "Me siento seguro/a en la escuela" },
                { codigo: "3", texto: "Mis profesores me ayudan cuando no entiendo" },
                { codigo: "4", texto: "En mi curso nos tratamos bien" },
                { codigo: "5", texto: "Cuando hay peleas, los adultos ayudan a solucionarlas" },
                { codigo: "6", texto: "Aprendo cosas interesantes" },
                { codigo: "7", texto: "Me escuchan cuando doy mi opinión" },
                { codigo: "8", texto: "Me siento orgulloso/a de mi escuela" },
                { codigo: "9", texto: "En mi escuela se trata igual a niñas y niños" },
              ],
            },
          ],
        },
        {
          codigo: "E3",
          numero: 3,
          tipo: "multiple",
          max: 2,
          texto: "¿Qué es lo MEJOR de tu escuela?",
          indicacion: "Marca máximo 2",
          opciones: [
            op(1, "Mis profesores"),
            op(2, "Mis compañeros y amigos"),
            op(3, "Lo que aprendo"),
            op(4, "Los talleres, el deporte y las actividades"),
            op(5, "La biblioteca y la lectura"),
            op(6, "Que me ayudan cuando me cuesta algo"),
            op(98, "No sé"),
            op(99, "Otra"),
          ],
        },
        {
          codigo: "E4",
          numero: 4,
          tipo: "multiple",
          max: 2,
          texto: "¿Qué te gustaría que MEJORARA?",
          indicacion: "Marca máximo 2",
          opciones: [
            op(1, "Los baños, patios y salas"),
            op(2, "Que haya menos peleas o bullying"),
            op(3, "Clases más entretenidas"),
            op(4, "Más talleres de deporte, arte o música"),
            op(5, "Usar más los computadores"),
            op(6, "Que escuchen más nuestra opinión"),
            op(98, "No sé"),
            op(99, "Otra"),
          ],
        },
      ],
    },
    {
      titulo: "La escuela que quiero",
      preguntas: [
        {
          codigo: "E5",
          numero: 5,
          tipo: "exacta",
          n: 2,
          texto: "¿Para qué sirve venir a la escuela?",
          indicacion: "Marca exactamente 2",
          opciones: L.PROP_ESTUDIANTES,
        },
        {
          codigo: "E6",
          numero: 6,
          tipo: "exacta",
          n: 3,
          texto: "¿Qué cosas debería cuidar tu escuela en los próximos años?",
          indicacion: "Marca exactamente 3",
          opciones: L.PRIORIDADES_ESTUDIANTES,
        },
        {
          codigo: "E7",
          numero: 7,
          tipo: "masImportante",
          de: "E6",
          texto: "De las 3 que marcaste, ¿cuál es la MÁS importante?",
          indicacion: "Marca una",
        },
        {
          codigo: "E8",
          numero: 8,
          tipo: "unica",
          texto: "¿Por qué es la más importante para ti?",
          indicacion: "Marca una",
          opciones: L.POR_ESTUDIANTES,
        },
        {
          codigo: "E9",
          numero: 9,
          tipo: "multiple",
          max: 2,
          texto: "¿Con qué lugares o grupos te gustaría que tu escuela hiciera más actividades?",
          indicacion: "Marca máximo 2",
          opciones: L.RED_ESTUDIANTES,
        },
        {
          codigo: "E10",
          numero: 10,
          tipo: "exacta",
          n: 3,
          texto: "¿Qué valores debería enseñar y cuidar más tu escuela?",
          indicacion: "Marca exactamente 3",
          opciones: L.VAL_ESTUDIANTES,
        },
        {
          codigo: "E11",
          numero: 11,
          tipo: "exacta",
          n: 3,
          texto: "Cuando termines 8° básico, me gustaría ser alguien que…",
          indicacion: "Marca exactamente 3",
          opciones: L.PER_ESTUDIANTES,
        },
        {
          codigo: "E12",
          numero: 12,
          tipo: "exacta",
          n: 3,
          texto: "Un buen profe es alguien que…",
          indicacion: "Marca exactamente 3",
          opciones: L.DOC_ESTUDIANTES,
        },
        {
          codigo: "E13",
          numero: 13,
          tipo: "abierta",
          texto: "Imagina tu escuela en el 2030. ¿Cómo te gustaría que fuera?",
          indicacion: "Opcional",
        },
        {
          codigo: "E14",
          numero: 14,
          tipo: "abierta",
          texto: "Si fueras director/a por un día, ¿qué cambiarías?",
          indicacion: "Opcional",
        },
      ],
    },
  ],
};
