// Encuesta Grupo 3 · Docentes y asistentes de la educación (v9 aprobada, 2/10/2026).
import type { Encuesta } from "./tipos";
import * as L from "./listas";
import { op } from "./listas";
import { MISION_ACTUAL, VISION_ACTUAL } from "./apoderados";

export const funcionarios: Encuesta = {
  estamento: "F",
  titulo: "Encuesta para docentes y asistentes de la educación",
  introduccion: [
    "Esta encuesta es parte del proceso de actualización del PEI. Es anónima y sus resultados serán procesados y presentados solo de forma agrupada. Las respuestas sobre gestión se informan en total o separadas solo entre docentes y asistentes, nunca por persona ni en grupos de menos de 5.",
    "Toma unos 19 minutos. Responda según su experiencia; si no tiene opinión, marque \"No sé\" o \"Prefiero no responder\" donde aparezca. Su credencial se sacó al azar: nadie sabe cuál recibió usted. En las respuestas escritas, por favor no escriba nombres de personas: si aparecen, se reemplazan antes de analizar.",
  ],
  minutos: 19,
  despedida: "¡Gracias por su aporte!",
  secciones: [
    {
      titulo: "Datos generales",
      preguntas: [
        {
          codigo: "F1",
          numero: 1,
          tipo: "unica",
          texto: "Función principal",
          opciones: [op(1, "Docente"), op(2, "Asistente de la educación")],
        },
      ],
    },
    {
      titulo: "Identidad actual",
      preguntas: [
        {
          codigo: "F2",
          numero: 2,
          tipo: "unica",
          texto: "¿Conoce el lema o los sellos actuales de la escuela?",
          opciones: L.CON_ADULTOS,
        },
        {
          codigo: "F3",
          numero: 3,
          tipo: "unica",
          cita: { antes: "La visión actual (PEI 2024–2026) dice:", texto: VISION_ACTUAL },
          texto: "¿Considera que sigue representando a la escuela?",
          opciones: L.VIG,
        },
        {
          codigo: "F4",
          numero: 4,
          tipo: "unica",
          cita: { antes: "La misión actual (PEI 2024–2026) dice:", texto: MISION_ACTUAL },
          texto: "¿Considera que sigue representando a la escuela?",
          opciones: L.VIG,
        },
        {
          codigo: "F5",
          numero: 5,
          tipo: "exacta",
          n: 2,
          texto: "¿Cuál debería ser el propósito principal de nuestra escuela?",
          indicacion: "Marque exactamente 2",
          opciones: L.PROP_ADULTOS,
        },
        {
          codigo: "F6",
          numero: 6,
          tipo: "multiple",
          max: 2,
          texto: "Según su experiencia, ¿en qué destaca HOY la escuela?",
          indicacion: "Marque máximo 2",
          opciones: [
            op(1, "Formación en valores y respeto"),
            op(2, "Calidad de los aprendizajes"),
            op(3, "Compromiso del equipo docente y asistente"),
            op(4, "Convivencia escolar"),
            op(5, "Fomento lector y biblioteca"),
            op(6, "Deporte y actividades extraprogramáticas"),
            op(7, "Apoyo a estudiantes con NEE (PIE)"),
            op(8, "Redes de apoyo con la comunidad (CESFAM, Carabineros, etc.)"),
            op(9, "Historia y tradición"),
            op(98, "No sé"),
            op(99, "Otra"),
          ],
        },
      ],
    },
    {
      titulo: "Diagnóstico de gestión",
      preguntas: [
        {
          codigo: "F7",
          numero: 7,
          tipo: "escala",
          escala: "ACU",
          texto: "¿Qué tan de acuerdo está con estas afirmaciones?",
          indicacion: "Marque una opción por frase",
          grupos: [
            {
              titulo: "Liderazgo y organización",
              items: [
                { codigo: "L1", texto: "Las decisiones del equipo directivo se comunican de forma clara y oportuna" },
                { codigo: "L2", texto: "La planificación y organización del año (calendario, horarios, reemplazos) es adecuada" },
                { codigo: "L3", texto: "Recibo acompañamiento y retroalimentación útil sobre mi trabajo" },
                { codigo: "L4", texto: "Existen instancias reales para participar en las decisiones" },
                { codigo: "L5", texto: "Los roles y responsabilidades de cada estamento están claros" },
              ],
            },
            {
              titulo: "Gestión pedagógica",
              items: [
                { codigo: "P1", texto: "El tiempo de clases se aprovecha para el aprendizaje" },
                { codigo: "P2", texto: "Accedo a capacitación pertinente para mi labor" },
                { codigo: "P3", texto: "Existe trabajo colaborativo entre docentes y asistentes" },
              ],
            },
            {
              titulo: "Convivencia y clima",
              items: [
                { codigo: "C1", texto: "Los protocolos de convivencia se aplican de forma consistente" },
                { codigo: "C2", texto: "Me siento valorado/a en mi trabajo" },
                { codigo: "C3", texto: "El clima laboral es respetuoso" },
                { codigo: "C4", texto: "Las familias participan activamente en el proceso educativo" },
                { codigo: "C5", texto: "La escuela promueve un trato igualitario entre hombres y mujeres" },
              ],
            },
            {
              titulo: "Gestión de recursos",
              items: [
                { codigo: "R1", texto: "Los recursos, materiales y espacios son suficientes para realizar bien mi trabajo" },
              ],
            },
          ],
        },
        {
          codigo: "F8",
          numero: 8,
          tipo: "multiple",
          max: 3,
          texto: "¿Cuáles son los principales nudos que traban el avance de la escuela hoy?",
          indicacion: "Marque máximo 3",
          opciones: [
            op(1, "Comunicación interna"),
            op(2, "Organización y planificación"),
            op(3, "Acompañamiento a la labor docente y asistente"),
            op(4, "Participación en la toma de decisiones"),
            op(5, "Convivencia escolar y manejo de conflictos"),
            op(6, "Compromiso de las familias"),
            op(7, "Uso del tiempo en el aula"),
            op(8, "Capacitación y desarrollo profesional"),
            op(9, "Carga administrativa"),
            op(10, "Infraestructura y recursos"),
            op(11, "Clima laboral"),
            op(99, "Otro"),
            op(97, "Prefiero no responder"),
          ],
        },
      ],
    },
    {
      titulo: "La escuela que queremos",
      preguntas: [
        {
          codigo: "F9",
          numero: 9,
          tipo: "exacta",
          n: 3,
          texto: "¿Cuáles de estas prioridades debería tener el nuevo Proyecto Educativo (PEI)?",
          indicacion: "Marque exactamente 3",
          opciones: L.PRIORIDADES_ADULTOS,
        },
        {
          codigo: "F10",
          numero: 10,
          tipo: "masImportante",
          de: "F9",
          texto: "De las tres que marcó, ¿cuál es la MÁS importante?",
          indicacion: "Marque una",
        },
        {
          codigo: "F11",
          numero: 11,
          tipo: "unica",
          texto: "¿Por qué es la más importante?",
          indicacion: "Marque una",
          opciones: L.POR_ADULTOS,
        },
        {
          codigo: "F12",
          numero: 12,
          tipo: "multiple",
          max: 2,
          texto: "¿Qué se necesita para lograrla?",
          indicacion: "Marque máximo 2",
          opciones: L.NEC,
        },
        {
          codigo: "F13",
          numero: 13,
          tipo: "multiple",
          max: 2,
          texto: "¿Cómo podría aportar usted?",
          indicacion: "Marque máximo 2",
          opciones: L.APO_F,
        },
        {
          codigo: "F14",
          numero: 14,
          tipo: "multiple",
          max: 2,
          texto: "¿Con qué instituciones u organizaciones debería colaborar más la escuela?",
          indicacion: "Marque máximo 2",
          opciones: L.RED_ADULTOS,
        },
        {
          codigo: "F15",
          numero: 15,
          tipo: "exacta",
          n: 3,
          texto: "¿Qué debería destacar y profundizar nuestra escuela en su enseñanza?",
          indicacion: "Marque exactamente 3",
          opciones: L.ENF,
        },
        {
          codigo: "F16",
          numero: 16,
          tipo: "exacta",
          n: 3,
          texto: "¿Qué valores deberían guiar a nuestra escuela?",
          indicacion: "Marque exactamente 3",
          opciones: L.VAL_ADULTOS,
        },
        {
          codigo: "F17",
          numero: 17,
          tipo: "exacta",
          n: 3,
          texto: "Al terminar 8° básico, un estudiante de nuestra escuela debería ser…",
          indicacion: "Marque exactamente 3",
          opciones: L.PER_ADULTOS,
        },
        {
          codigo: "F18",
          numero: 18,
          tipo: "exacta",
          n: 3,
          texto: "Un buen profesor o profesora de nuestra escuela es alguien que…",
          indicacion: "Marque exactamente 3",
          opciones: L.DOC_ADULTOS,
        },
        {
          codigo: "F19",
          numero: 19,
          tipo: "exacta",
          n: 3,
          texto: "En nuestra escuela, una familia comprometida es aquella que…",
          indicacion: "Marque exactamente 3",
          opciones: L.FAM,
        },
        {
          codigo: "F20",
          numero: 20,
          tipo: "abierta",
          texto:
            "Imagine que en el 2030 una familia nueva pregunta por nuestra escuela. ¿Cómo le gustaría que la describieran?",
          indicacion: "Opcional",
        },
        {
          codigo: "F21",
          numero: 21,
          tipo: "abierta",
          texto: "¿Qué cambio concreto propondría para mejorar la escuela en los próximos años?",
          indicacion: "Opcional",
        },
      ],
    },
  ],
};
